import ResumeHeader from "./ResumeHeader";
import ResumeSection from "./ResumeSection";
import SkillBadge from "./SkillBadge";

export default function ResumeTemplate({ profile, resume }) {
  if (!profile || !resume) return null;

  return (
    <div
      id="resume-template"
      className="bg-white text-gray-900 shadow-2xl rounded-xl p-10 mt-8 max-w-5xl mx-auto"
    >
      <ResumeHeader profile={profile} />

      <ResumeSection title="Professional Summary">
        <p>{resume.summary}</p>
      </ResumeSection>

      <ResumeSection title="Technical Skills">
        <div className="flex flex-wrap gap-3">
          {resume.skills?.map((skill) => (
            <SkillBadge key={skill} skill={skill} />
          ))}
        </div>
      </ResumeSection>

      <ResumeSection title="Training">
        {resume.training?.length ? (
          <ul className="list-disc pl-6 space-y-2">
            {resume.training.map((item, index) => (
              <li key={index}>{item}</li>
            ))}
          </ul>
        ) : (
          <p>No training information available.</p>
        )}
      </ResumeSection>

      <ResumeSection title="Projects">
        <div className="space-y-5">
          {resume.projects?.map((project, index) => (
            <div key={index}>
              <h3 className="font-bold text-lg">
                {project.name}
              </h3>

              <p className="text-gray-700">
                {project.description}
              </p>
            </div>
          ))}
        </div>
      </ResumeSection>

      <ResumeSection title="Certificates">
        {resume.certificates?.length ? (
          <ul className="list-disc pl-6 space-y-2">
            {resume.certificates.map((certificate, index) => (
              <li key={index}>{certificate}</li>
            ))}
          </ul>
        ) : (
          <p>No certificates available.</p>
        )}
      </ResumeSection>

      <ResumeSection title="Education">
        <div className="space-y-2">
          <p>
            <strong>College:</strong>{" "}
            {resume.education?.college || "Not Available"}
          </p>

          <p>
            <strong>Degree:</strong>{" "}
            {resume.education?.degree || "Not Available"}
          </p>

          <p>
            <strong>CGPA:</strong>{" "}
            {resume.education?.cgpa || "Not Available"}
          </p>
        </div>
      </ResumeSection>

      <div className="border-t mt-10 pt-5 text-center text-gray-500 text-sm">
        Generated by CodeVista AI Resume Builder 🚀
      </div>
    </div>
  );
}